server:
  port: ${API_GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: report-service
              uri: lb://report-service
              predicates:
                - Path=/api/reports/**